FUNDI_WELCOME_MESSAGE: "Education to Empower Africa!"
FUNDI_PRIMARY_COLOR: "#b06660" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# FUNDI_FOOTER_NAV_LINKS: []
# FUNDI_FOOTER_LEGAL_LINKS: []
FUNDI_FOOTER_NAV_LINKS: []
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
FUNDI_FOOTER_LEGAL_LINKS: []
    - title: "Terms of service"
      url: "/tos"
    - title: "Education to Empower Africa!"
      url: "https://fundiacademy.com"
